includes("lib/commonlibf4")

option("dotnet_host_dir")
    set_showmenu(true)
    set_description("Microsoft.NETCore.App.Host.win-x64 native directory")
option_end()

set_project("F4Forge")
set_version("0.1.0")
set_license("MIT")
set_languages("c++23")
set_warnings("allextra")

add_rules("mode.debug", "mode.releasedbg")
add_rules("plugin.vsxmake.autoupdate")

target("F4Forge")
    set_kind("shared")
    add_rules("commonlibf4.plugin", {
        name = "F4Forge",
        author = "F4Forge contributors",
        description = "Generic runtime host for Fallout 4 plugins"
    })
    add_files("src/**.cpp", "core/**.cpp")
    add_headerfiles("src/**.h")
    add_includedirs("src", "abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })
    set_pcxxheader("src/pch.h")

target("F4ForgeAbiTests")
    set_kind("binary")
    add_files("tests/abi/AbiTests.cpp")
    add_includedirs("abi")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeAbiCCompile")
    set_kind("binary")
    add_files("tests/abi/AbiCCompile.c")
    add_includedirs("abi")
    add_cflags("/WX", "/TC", { public = false })

target("F4ForgeRegistryTests")
    set_kind("binary")
    add_files("core/registry/endpoint_registry.cpp", "tests/registry/EndpointRegistryTests.cpp")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeModuleTests")
    set_kind("binary")
    add_files("core/async/*.cpp", "core/registry/*.cpp", "core/runtime/runtime_manager.cpp", "core/modules/module_manager.cpp", "tests/modules/ModuleManagerTests.cpp")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeLifecycleTests")
    set_kind("binary")
    add_files("tests/lifecycle/DispatchOwnerTests.cpp")
    add_includedirs("core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeDependencyTests")
    set_kind("binary")
    add_files("core/modules/dependency_graph.cpp", "tests/modules/DependencyGraphTests.cpp")
    add_includedirs("core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeHostTests")
    set_kind("binary")
    add_files("core/async/*.cpp", "core/registry/*.cpp", "core/modules/module_manager.cpp", "core/runtime/runtime_manager.cpp", "core/f4forge_host.cpp", "tests/host/F4ForgeHostTests.cpp")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeEventTests")
    set_kind("binary")
    add_files("core/registry/*.cpp", "tests/registry/EventInterceptorRegistryTests.cpp")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeCapabilityTests")
    set_kind("binary")
    add_files("core/registry/capability_registry.cpp", "tests/registry/CapabilityRegistryTests.cpp")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeRuntimeTests")
    set_kind("binary")
    add_files("core/runtime/runtime_manager.cpp", "tests/runtime/RuntimeManagerTests.cpp")
    add_deps("F4Forge.TestA", "F4Forge.TestB")
    add_includedirs("abi", "core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4Forge.TestA")
    set_kind("shared")
    set_basename("F4Forge.TestA")
    set_targetdir("build/runtime-fixtures")
    add_files("tests/runtime/FakeProviderA.cpp")
    add_includedirs("abi")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4Forge.TestB")
    set_kind("shared")
    set_basename("F4Forge.TestB")
    set_targetdir("build/runtime-fixtures")
    add_files("tests/runtime/FakeProviderB.cpp")
    add_includedirs("abi")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4ForgeConfigTests")
    set_kind("binary")
    add_files("core/config/config.cpp", "tests/config/ConfigTests.cpp")
    add_includedirs("core")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })

target("F4Forge.Dotnet")
    set_basename("F4Forge.Dotnet")
    set_kind("shared")
    set_targetdir("../runtimes/dotnet/native-provider/bin")
    add_files("../runtimes/dotnet/native-provider/DotNetProvider.cpp", "../runtimes/dotnet/native-provider/HostFxrVersion.cpp")
    if os.isfile("generated/dotnet_runtime.rc") then
        add_files("generated/dotnet_runtime.rc")
    end
    add_includedirs("abi")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })
    on_load(function(target)
        local hostdir = get_config("dotnet_host_dir")
        assert(hostdir and os.isfile(path.join(hostdir, "hostfxr.h")), "Missing .NET x64 native host pack")
        target:add("includedirs", hostdir)
    end)

target("F4ForgeHostFxrVersionTests")
    set_kind("binary")
    add_files("../runtimes/dotnet/native-provider/HostFxrVersion.cpp", "tests/runtime/HostFxrVersionTests.cpp")
    add_includedirs("../runtimes/dotnet/native-provider")
    add_cxxflags("/WX", "/permissive-", "/EHsc", "/utf-8", { public = false })
